field: b3e1c9f3-7e40-4ec9-9d9d-96fa163a671c
fieldLayouts:
  9af988b6-a529-4ee7-89d2-fc7d02d24f72:
    tabs:
      -
        elements:
          -
            fieldUid: aad8061a-3033-4a2c-be24-a690c2f48426
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: caa54966-219c-4c07-89f7-5cc57a3cb6a4
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  aad8061a-3033-4a2c-be24-a690c2f48426:
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: 'Double click for more options.'
    name: Images
    searchable: true
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:da05715e-f118-4c6e-b946-1b87d681d043'
      defaultUploadLocationSubpath: ''
      limit: '12'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Choose Images'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:da05715e-f118-4c6e-b946-1b87d681d043'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:da05715e-f118-4c6e-b946-1b87d681d043'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  caa54966-219c-4c07-89f7-5cc57a3cb6a4:
    contentColumnType: boolean
    fieldGroup: null
    handle: hideImageBorders
    instructions: ''
    name: 'Hide Image Borders'
    searchable: true
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: gallery
name: 'Image Gallery'
sortOrder: 7
