fieldLayouts:
  a059b04a-6b5c-4385-be8d-89d53395543d:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 626d91be-b8e9-41e6-87c2-0a08f57d9d92
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0b0ef870-0127-4663-b045-1f00b6f700a5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a5703536-4f6d-43a4-bf56-03d93e13bd8a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ae5298d0-8399-442c-a5c6-5d45859b79af
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: blogList
hasTitleField: true
name: 'Blog Post List'
section: 07d38a58-4d79-4d5d-a086-28c6f4453df0
sortOrder: 0
titleFormat: ''
