fieldLayouts:
  82f9c852-77c8-4ade-b1f9-65e97d54aa4a:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 626d91be-b8e9-41e6-87c2-0a08f57d9d92
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0b0ef870-0127-4663-b045-1f00b6f700a5
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: a5703536-4f6d-43a4-bf56-03d93e13bd8a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ae5298d0-8399-442c-a5c6-5d45859b79af
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b3e1c9f3-7e40-4ec9-9d9d-96fa163a671c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
      -
        name: Sidebar
        sortOrder: 2
handle: page
hasTitleField: true
name: 'Two Column Page'
section: 07d38a58-4d79-4d5d-a086-28c6f4453df0
sortOrder: 0
titleFormat: ''
