contentColumnType: string
fieldGroup: 7025c78b-3031-405b-9845-6889983aae90
handle: body
instructions: ''
name: Body
searchable: true
settings:
  cleanupHtml: '1'
  columnType: text
  configFile: Standard.json
  purifyHtml: ''
translationKeyFormat: null
translationMethod: none
type: craft\redactor\Field
