contentColumnType: string
fieldGroup: 7025c78b-3031-405b-9845-6889983aae90
handle: image
instructions: ''
name: Image
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:da05715e-f118-4c6e-b946-1b87d681d043'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Choose Image'
  singleUploadLocationSource: 'volume:da05715e-f118-4c6e-b946-1b87d681d043'
  singleUploadLocationSubpath: ''
  sources:
    - 'volume:da05715e-f118-4c6e-b946-1b87d681d043'
  useSingleFolder: '1'
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
