contentColumnType: text
fieldGroup: 7025c78b-3031-405b-9845-6889983aae90
handle: preview
instructions: 'A short summary of the content.'
name: Synopsis
searchable: true
settings:
  charLimit: ''
  columnType: text
  initialRows: '3'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
