enableVersioning: false
handle: blog
name: Blog
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ae98859a-dab4-4af3-b70d-780ede8c6184:
    enabledByDefault: true
    hasUrls: true
    template: blog/_entry
    uriFormat: 'post/{slug}'
type: channel
