enableVersioning: false
handle: homepage
name: 'Home Page'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  ae98859a-dab4-4af3-b70d-780ede8c6184:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
