enableVersioning: false
handle: pages
name: Navigation
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  ae98859a-dab4-4af3-b70d-780ede8c6184:
    enabledByDefault: true
    hasUrls: true
    template: pages/_typeSelect
    uriFormat: '{% if object.level == 1 %}{slug}{% else %}{parent.uri}/{slug}{% endif %}'
structure:
  maxLevels: 2
  uid: c08449ef-8bde-4df3-8e34-564d885d830d
type: structure
