enableVersioning: true
handle: sermonTopics
name: Topics
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  ae98859a-dab4-4af3-b70d-780ede8c6184:
    enabledByDefault: true
    hasUrls: true
    template: sermons/_sort
    uriFormat: 'sermons/topic/{slug}'
structure:
  maxLevels: 1
  uid: 0285fa06-2858-4195-bc75-ee47edb62816
type: structure
